# -*- coding: utf-8 -*-
"""Projet Deep Learning CNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTOnjUW2N4fCZFIqRZSvaitwJFuER-cb

# Convolutional Neural Networks (CNN)
author : [Maxime Devanne](https://www.maxime-devanne.com)

### Import libraries
"""

from sklearn.preprocessing import normalize
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import random

import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import MinMaxScaler

"""## Pokemon images dataset

### Downloading
"""

!wget https://maxime-devanne.com/datasets/ECG200/ECG200_TRAIN.tsv
!wget https://maxime-devanne.com/datasets/ECG200/ECG200_TEST.tsv

"""### Reading the dataset"""

dfTrain = pd.read_csv("ECG200_TRAIN.tsv", sep='\t')
dfTest = pd.read_csv("ECG200_TEST.tsv", sep='\t')

"""#### Dataset preparation

##### Cleaning
"""

dfTrain = dfTrain.dropna()
dfTest = dfTest.dropna()

"""##### Extraction of input data"""

X_train = np.asarray(dfTrain.iloc[:, 1:], dtype=np.float32)
X_test = np.asarray(dfTest.iloc[:, 1:], dtype=np.float32)

print(X_train.shape)
print(X_test.shape)

"""##### Preparing output data (class labels)"""

y_train = np.asarray(dfTrain.iloc[:, 0], dtype=np.float32)
y_test = np.asarray(dfTest.iloc[:, 0], dtype=np.float32)

le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

ohe = OneHotEncoder()
y_train = ohe.fit_transform(y_train.reshape(-1,1)).toarray()
y_test = ohe.transform(y_test.reshape(-1,1)).toarray()

print(y_train.shape)
print(y_test.shape)

"""##### Normalization"""

scaler = MinMaxScaler().fit(X_train)
x_train = scaler.transform(X_train)
x_train = x_train.reshape((x_train.shape[0], x_train.shape[1], 1))
x_test = scaler.transform(X_test)
x_test = x_test.reshape((x_test.shape[0], x_test.shape[1], 1))

"""## Train the convolutional neural network

### Create the input layer which has the same shape as that of an instance in `x_train`
"""

input_shape = x_train.shape[1:]

input_layer = tf.keras.layers.Input(input_shape)

"""### Create a hidden convolutional layer that contains 8 filters with the `relu` activation"""

padding = 'same'
stride = 1
kernel_size = 3
filters = 8
activation = 'relu'

hidden_conv_layer_1 = tf.keras.layers.Conv1D(
    filters=filters,
    kernel_size=kernel_size,
    strides=stride,
    padding=padding,
    activation=activation
)(input_layer)

"""### Link a max pooling to the convolutional layer"""

pool_size = 2
stride = 2
padding = 'valid'
pooling_conv_layer_1 = tf.keras.layers.MaxPooling1D(pool_size = pool_size, strides = stride,
                                          padding=padding)(hidden_conv_layer_1)

"""### Flatten the output of pooling"""

flattened_layer_1 = tf.keras.layers.Flatten()(pooling_conv_layer_1)

"""### Create the output layer"""

nb_classes = y_train.shape[1]
output_layer = tf.keras.layers.Dense(units=nb_classes,activation='softmax')(flattened_layer_1)

"""### Create the model now"""

model_cnn = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)

"""### View model information"""

model_cnn.summary()

"""### Choose the optimization algorithm with a learning rate of 0.01"""

learning_rate = 0.001
optimizer_algo = tf.keras.optimizers.Adam(learning_rate=learning_rate)

"""### Choose the cost function you want to optimize: (Categorical Cross-Entropy)"""

cost_function = tf.keras.losses.categorical_crossentropy

"""### Compile the model by indicating to it that we also want to measure the accuracy"""

model_cnn.compile(loss=cost_function,optimizer=optimizer_algo, metrics=['accuracy'])

"""### Specify the fact that we want to save the best model on the valdiation set"""

model_checkpoint = tf.keras.callbacks.ModelCheckpoint('best-model.keras', monitor='val_loss', save_best_only=True)

"""## Training

### Choose the batch size and the number of epochs
"""

mini_batch_size = 256
nb_epochs = 500

"""### Train by specifying to use part of the train for the validation of hyper-parameters

Be patient :-)
"""

percentage_of_train_as_validation = 0.3
history_cnn = model_cnn.fit(x_train,y_train,batch_size=mini_batch_size,
                    epochs=nb_epochs,verbose=False,
                    validation_split=percentage_of_train_as_validation,
                    callbacks=[model_checkpoint])

"""### Plot the variation of the error rate on the train and on the validation set according to the number of epochs"""

history_dict = history_cnn.history
loss_train_epochs = history_dict['loss']
loss_val_epochs = history_dict['val_loss']

plt.figure()
plt.plot(loss_train_epochs,color='blue',label='train_loss')
plt.plot(loss_val_epochs,color='red',label='val_loss')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()
plt.savefig('epoch-loss.pdf')
plt.show()
plt.close()

"""### Choose the saved model"""

model_cnn = tf.keras.models.load_model('best-model.keras')

"""### Evaluate the saved model on train and test"""

loss,acc = model_cnn.evaluate(x_train,y_train,verbose=False)

print("Accuracy on train:",acc)

loss,acc = model_cnn.evaluate(x_test,y_test,verbose=False)

print("Accuracy on test:",acc)

"""**=>This is our first CNN!**

## **Exercices**

In this exercice, the goal is to build, train and evaluate the model of slide 56 (ignoring the dropout). Particularly, you have to:


*   Build the model
*   Plot the variation of the accuracy (not only the loss) as a function of the number of epochs (so use 'accuracy' instead of 'loss')
*   Display the summary of your model
*   Evaluate your model
"""

# Your code here

"""### Correction :

#### Build the model of slide 56 ignoring the dropout
"""

nb_classes = y_train.shape[1]
input_shape = x_train.shape[1:]
input_layer = tf.keras.layers.Input(input_shape)
hidden_conv_layer_1 = tf.keras.layers.Conv1D(filters=10, padding='valid',
                                          kernel_size=5, strides=1,
                                         activation='relu')(input_layer)
hidden_pooling_layer_1 = tf.keras.layers.MaxPooling1D(pool_size=2, strides=2,
                                                  padding='valid')(hidden_conv_layer_1)
hidden_conv_layer_2 = tf.keras.layers.Conv1D(filters=20, padding='valid',
                                          kernel_size=5, strides=1,
                                          activation='relu')(hidden_pooling_layer_1)
hidden_pooling_layer_2 = tf.keras.layers.MaxPooling1D(pool_size=2, strides=2,
                                                padding='valid')(hidden_conv_layer_2)
flatenned_layer_2 = tf.keras.layers.Flatten()(hidden_pooling_layer_2)
dense_layer = tf.keras.layers.Dense(units=100, activation='relu')(flatenned_layer_2)
output_layer = tf.keras.layers.Dense(units=nb_classes, activation='softmax')(dense_layer)

model_cnn2 = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)
learning_rate = 0.001
optimizer_algo = tf.keras.optimizers.Adam(learning_rate=learning_rate)
cost_function = tf.keras.losses.categorical_crossentropy
model_cnn2.compile(loss=cost_function,optimizer=optimizer_algo, metrics=['accuracy'])
mini_batch_size = 256
nb_epochs = 500
model_checkpoint = tf.keras.callbacks.ModelCheckpoint('best-model.keras', monitor='val_loss', save_best_only=True)
percentage_of_train_as_validation = 0.3
history_cnn2 = model_cnn2.fit(x_train,y_train,batch_size=mini_batch_size,epochs=nb_epochs,
                    validation_split=percentage_of_train_as_validation,verbose=False,
                   callbacks=[model_checkpoint])

"""#### Plot the variation of the accuracy (not the cost) as a function of the number of epochs (so use 'acc' instead of 'loss')"""

history_dict2 = history_cnn2.history
acc_train_epochs = history_dict2['accuracy']
acc_val_epochs = history_dict2['val_accuracy']

plt.figure()
plt.plot(acc_train_epochs,color='blue',label='train_acc')
plt.plot(acc_val_epochs,color='red',label='val_acc')
plt.xlabel('epoch')
plt.ylabel('accuracy')
plt.legend()
plt.show()
plt.close()

"""#### Display the summary of your model and analyze the output (this step can be done before training)"""

model_cnn2.summary()

"""#### Choose saved model"""

model_cnn2 = tf.keras.models.load_model('best-model.keras')

"""#### Evaluate model"""

# evaluation on train
loss,acc = model_cnn2.evaluate(x_train,y_train,verbose=False)
print("Accuracy on train:",acc)

# evaluation on test
loss,acc = model_cnn2.evaluate(x_test,y_test,verbose=False)
print("Accuracy on test:",acc)