# -*- coding: utf-8 -*-
"""Projet Deep Learning MLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtH3XCd6AVG0HwHAqZCgd0O2vVumNnYW

# Multi-Layer Perceptron (MLP)
author : [Maxime Devanne](https://www.maxime-devanne.com)

## Import librairies
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf

"""## Classification

### ECG Dataset

#### Downloading the dataset
"""

!wget https://maxime-devanne.com/datasets/ECG200/ECG200_TRAIN.tsv
!wget https://maxime-devanne.com/datasets/ECG200/ECG200_TEST.tsv

"""#### Reading the dataset"""

dfTrain = pd.read_csv("ECG200_TRAIN.tsv", sep='\t')
dfTest = pd.read_csv("ECG200_TEST.tsv", sep='\t')
dfTrain.head()
dfTest.head()

"""#### Dataset preparation

##### Cleaning
"""

dfTrain = dfTrain.dropna()
dfTest = dfTest.dropna()

"""##### Extraction of input data"""

XTrain = np.asarray(dfTrain.iloc[:, 1:], dtype=np.float32)
XTest = np.asarray(dfTest.iloc[:, 1:], dtype=np.float32)

print(XTrain.shape)
print(XTest.shape)

"""##### Preparing output data (class labels)

In a multi-class classification, we need to have a one-hot vector representation of labels.
"""

yTrain = np.asarray(dfTrain.iloc[:, 0], dtype=np.float32)
yTest = np.asarray(dfTest.iloc[:, 0], dtype=np.float32)

le = LabelEncoder()
yTrain = le.fit_transform(yTrain)
yTest = le.transform(yTest)

ohe = OneHotEncoder()
yTrain = ohe.fit_transform(yTrain.reshape(-1,1)).toarray()
yTest = ohe.transform(yTest.reshape(-1,1)).toarray()

print(yTrain.shape)
print(yTest.shape)

"""##### Normalization"""

scaler = MinMaxScaler().fit(XTrain)
XTrain = scaler.transform(XTrain)
XTest = scaler.transform(XTest)

"""### Building a MLP

#### Input layer
"""

input_shape = XTrain.shape[1:]
input_layer = tf.keras.layers.Input(input_shape)

"""#### Hidden layer
Includes 16 neurons with a `sigmoid` activation
"""

# the hidden layer is connected to the input layer
hidden_layer = tf.keras.layers.Dense(units=16, activation='sigmoid')(input_layer)

"""#### Output layer
Includes as many neurones as the number of classes, and uses a `softmax` activation

"""

nb_classes = yTrain.shape[1]
output_layer = tf.keras.layers.Dense(units=nb_classes,activation='softmax')(hidden_layer)

"""#### Creating the MLP model"""

model_mlp = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)

"""#### Visualizing the model"""

# textual information
model_mlp.summary()

# connected graph
tf.keras.utils.plot_model(model_mlp, show_shapes=True)

"""#### Compilation of the model
We have to specify :
- the optimization algorithm with the learning rate
- the cost function
- an additional metric (optionnal)
"""

# Optimizer : Adam
learning_rate = 0.001
optimizer_algo = tf.keras.optimizers.Adam(learning_rate=learning_rate)

# Cost function : Categorical Cross-Entropy
cost_function = tf.keras.losses.categorical_crossentropy

# Model compilation with the 'accuracy' as additional metric
model_mlp.compile(loss=cost_function,optimizer=optimizer_algo, metrics=['accuracy'])

"""### Training the MLP"""

nb_epochs = 1000
mini_batch_size = 32
percentage_of_train_as_validation = 0.2
model_checkpoint = tf.keras.callbacks.ModelCheckpoint('best-model.keras', monitor='val_loss', save_best_only=True)

"""#### Running the training
It is possible to put the hyper-parameter `verbose` to `False` to not see results at each epoch

**Be patient :)**
"""

history_mlp = model_mlp.fit(XTrain,yTrain,batch_size=mini_batch_size,
                    epochs=nb_epochs,verbose=True,
                    validation_split=percentage_of_train_as_validation,
                    callbacks=[model_checkpoint])

"""You now have a 'best-model.keras' saved in the environment.

### Plot the loss variation
"""

history_dict = history_mlp.history
loss_train_epochs = history_dict['loss']
loss_val_epochs = history_dict['val_loss']

plt.figure()
plt.plot(loss_train_epochs,color='blue',label='train_loss')
plt.plot(loss_val_epochs,color='red',label='val_loss')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()
plt.savefig('epoch-loss.pdf')
plt.show()
plt.close()

"""### Choose the best model"""

model = tf.keras.models.load_model('best-model.keras')

"""### Evaluate its performance on the test set"""

loss,acc = model.evaluate(XTest,yTest)

print("Accuracy on the test set:",acc)

"""### **Exercises**

#### Try to improve the model by adding a second hidden layer with 16 neurons. Compare the results.
"""

input_shape = XTrain.shape[1:]
input_layer = tf.keras.layers.Input(input_shape)
hidden_layer = tf.keras.layers.Dense(units=16, activation='sigmoid')(input_layer)
hidden_layer2 = tf.keras.layers.Dense(units=16, activation='sigmoid')(hidden_layer)
output_layer = tf.keras.layers.Dense(units=nb_classes,activation='softmax')(hidden_layer2)
# create a new model
model_mlp2 = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)
model_mlp2.summary()

learning_rate = 0.001
optimizer_algo = tf.keras.optimizers.Adam(learning_rate=learning_rate)
cost_function = tf.keras.losses.categorical_crossentropy

model_mlp2.compile(loss=cost_function,optimizer=optimizer_algo, metrics=['accuracy'])

# create a new checkpoint if we want to save the model with a new name
nb_epochs = 1000
mini_batch_size = 32
percentage_of_train_as_validation = 0.2
model_checkpoint = tf.keras.callbacks.ModelCheckpoint('best-model2.keras', monitor='val_loss', save_best_only=True)

history_mlp2 = model_mlp2.fit(XTrain,yTrain,batch_size=mini_batch_size,
                    epochs=nb_epochs,verbose=False,
                    validation_split=percentage_of_train_as_validation,
                    callbacks=[model_checkpoint])

history_dict = history_mlp2.history
loss_train_epochs = history_dict['loss']
loss_val_epochs = history_dict['val_loss']

plt.figure()
plt.plot(loss_train_epochs,color='blue',label='train_loss')
plt.plot(loss_val_epochs,color='red',label='val_loss')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()
plt.savefig('epoch-loss.pdf')
plt.show()
plt.close()

model2 = tf.keras.models.load_model('best-model2.keras')
loss,acc = model2.evaluate(XTest,yTest)
print("Accuracy on the test set:",acc)

"""#### Try to remove non-linear activation in hidden layer and put them as linear (activation='linear'). Compare the results"""

input_shape = XTrain.shape[1:]
input_layer = tf.keras.layers.Input(input_shape)
hidden_layer = tf.keras.layers.Dense(units=16, activation='linear')(input_layer)
hidden_layer2 = tf.keras.layers.Dense(units=16, activation='linear')(hidden_layer)
output_layer = tf.keras.layers.Dense(units=nb_classes,activation='softmax')(hidden_layer2)
# create a new model
model_mlp3 = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)
model_mlp3.summary()

learning_rate = 0.001
optimizer_algo = tf.keras.optimizers.Adam(learning_rate=learning_rate)
cost_function = tf.keras.losses.categorical_crossentropy

model_mlp3.compile(loss=cost_function,optimizer=optimizer_algo, metrics=['accuracy'])

# create a new checkpoint if we want to save the model with a new name
nb_epochs = 1000
mini_batch_size = 32
percentage_of_train_as_validation = 0.2
model_checkpoint = tf.keras.callbacks.ModelCheckpoint('best-model3.keras', monitor='val_loss', save_best_only=True)

history_mlp3 = model_mlp3.fit(XTrain,yTrain,batch_size=mini_batch_size,
                    epochs=nb_epochs,verbose=False,
                    validation_split=percentage_of_train_as_validation,
                    callbacks=[model_checkpoint])

history_dict = history_mlp3.history
loss_train_epochs = history_dict['loss']
loss_val_epochs = history_dict['val_loss']

plt.figure()
plt.plot(loss_train_epochs,color='blue',label='train_loss')
plt.plot(loss_val_epochs,color='red',label='val_loss')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()
plt.savefig('epoch-loss.pdf')
plt.show()
plt.close()

model3 = tf.keras.models.load_model('best-model3.keras')
loss,acc = model3.evaluate(XTest,yTest)
print("Accuracy on the test set:",acc)