# -*- coding: utf-8 -*-
"""Projet Deep Learning MLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VRtIz7roHGILwjUkP2to3epKhThkNmzh

Authors: [Maxime Devanne](https://maxime-devanne.com), [Germain Forestier](https://germain-forestier.info/), [Hassan Ismail Fawaz](https://hfawaz.github.io) and [Jonathan Weber](http://jonathan-weber.eu/)

#**Recurrent Neural Networks**

## Import librairies
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler
import tensorflow as tf
import time # Importé pour l'étude de complexité temporelle

"""## Classification

### ECG Dataset

#### Downloading the dataset
"""

!wget https://maxime-devanne.com/datasets/ECG200/ECG200_TRAIN.tsv
!wget https://maxime-devanne.com/datasets/ECG200/ECG200_TEST.tsv

"""#### Reading the dataset"""

print("Lecture et préparation des données...")
dfTrain = pd.read_csv("ECG200_TRAIN.tsv", sep='\t').dropna()
dfTest = pd.read_csv("ECG200_TEST.tsv", sep='\t').dropna()

"""#### Dataset preparation

##### Extraction of input data"""

X_train = np.asarray(dfTrain.iloc[:, 1:], dtype=np.float32)
X_test = np.asarray(dfTest.iloc[:, 1:], dtype=np.float32)

"""##### Preparing output data (class labels)

In a multi-class classification, we need to have a one-hot vector representation of labels.
"""

y_train = np.asarray(dfTrain.iloc[:, 0], dtype=np.float32)
y_test = np.asarray(dfTest.iloc[:, 0], dtype=np.float32)

le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

ohe = OneHotEncoder()
y_train = ohe.fit_transform(y_train.reshape(-1,1)).toarray()
y_test = ohe.transform(y_test.reshape(-1,1)).toarray()

"""##### Normalization"""

scaler = MinMaxScaler().fit(X_train)
x_train = scaler.transform(X_train)
x_test = scaler.transform(X_test)

"""##### Reshaping for RNN

ATTENTION : Reshape spécifique pour les RNN/LSTM
Un RNN attend une entrée 3D : (nb_samples, time_steps, features)
Ici, les "time_steps" sont les points du signal ECG, et "features" = 1 (l'amplitude)
"""

x_train = x_train.reshape((x_train.shape[0], x_train.shape[1], 1))
x_test = x_test.reshape((x_test.shape[0], x_test.shape[1], 1))

print("Shape X_train formaté pour RNN :", x_train.shape)
print("Shape y_train :", y_train.shape)


"""### Building a RNN (LSTM)

#### Input layer
"""

input_shape = x_train.shape[1:]
input_layer = tf.keras.layers.Input(shape=input_shape)

"""#### Hidden layer
Couche LSTM (Long Short-Term Memory, plus performante que SimpleRNN pour l'ECG)
On utilise 64 neurones.
"""

hidden_rnn = tf.keras.layers.LSTM(units=64)(input_layer)

"""#### Output layer
Couche de sortie pour la classification
"""

nb_classes = y_train.shape[1]
output_layer = tf.keras.layers.Dense(units=nb_classes, activation='softmax')(hidden_rnn)

"""#### Creating the RNN model"""

model_rnn = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)

"""#### Visualizing the model"""

model_rnn.summary()

"""#### Compilation of the model
We have to specify :
- the optimization algorithm with the learning rate
- the cost function
- an additional metric (optionnal)
"""

learning_rate = 0.001
optimizer_algo = tf.keras.optimizers.Adam(learning_rate=learning_rate)
cost_function = tf.keras.losses.categorical_crossentropy

model_rnn.compile(loss=cost_function, optimizer=optimizer_algo, metrics=['accuracy'])

"""### Training the RNN"""

nb_epochs = 200 # Les RNN convergent souvent plus vite mais sont plus longs à calculer par epoch
mini_batch_size = 32
percentage_of_train_as_validation = 0.2
model_checkpoint = tf.keras.callbacks.ModelCheckpoint('best-model-rnn.keras', monitor='val_loss', save_best_only=True)

"""#### Running the training
Les RNN convergent souvent plus vite mais sont plus longs à calculer par epoch
It is possible to put the hyper-parameter `verbose` to `False` to not see results at each epoch

**Be patient :)**
"""

print("\nDébut de l'entraînement...")
start_train_time = time.time()

history_rnn = model_rnn.fit(x_train, y_train, 
                            batch_size=mini_batch_size,
                            epochs=nb_epochs, 
                            verbose=False, # Mettre à True pour voir la progression
                            validation_split=percentage_of_train_as_validation,
                            callbacks=[model_checkpoint])

end_train_time = time.time()
training_duration = end_train_time - start_train_time
print(f"Temps d'entraînement total : {training_duration:.2f} secondes")


"""### Plot the loss variation"""

history_dict = history_rnn.history

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_dict['loss'], color='blue', label='train_loss')
plt.plot(history_dict['val_loss'], color='red', label='val_loss')
plt.title('Loss du modèle RNN')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_dict['accuracy'], color='blue', label='train_acc')
plt.plot(history_dict['val_accuracy'], color='red', label='val_acc')
plt.title('Accuracy du modèle RNN')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.savefig('epoch-metrics-rnn.pdf')
plt.show()
plt.close()

"""### Choose the best model"""

best_model_rnn = tf.keras.models.load_model('best-model-rnn.keras')

"""### Evaluate its performance on the test set"""

# Mesure du temps d'inférence (sur le set de test complet)
start_infer_time = time.time()
loss, acc = best_model_rnn.evaluate(x_test, y_test, verbose=False)
end_infer_time = time.time()

inference_duration = end_infer_time - start_infer_time

print("\n--- RÉSULTATS DU MODÈLE RNN ---")
print(f"Accuracy sur le set de test : {acc*100:.2f}%")
print(f"Temps d'inférence pour {x_test.shape[0]} signaux : {inference_duration:.4f} secondes")
print(f"Temps d'inférence par signal : {(inference_duration/x_test.shape[0])*1000:.2f} millisecondes")

# Nombre de paramètres (Complexité spatiale)
print(f"Nombre total de paramètres entraînables : {best_model_rnn.count_params()}")